import {
  Activity,
  AlertTriangle,
  Book,
  Box,
  Calculator,
  Clock,
  Code,
  Cpu,
  Database,
  DatabaseBackup,
  Eye,
  Feather,
  FileText,
  Filter,
  Flame,
  Folder,
  FolderTree,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Infinity,
  Keyboard,
  Layers,
  Layout,
  Link,
  List,
  Lock,
  MoreHorizontal,
  Network,
  Package,
  RefreshCw,
  Repeat,
  Save,
  ScrollText,
  Search,
  Server,
  Settings,
  Shield,
  Terminal,
  TerminalSquare,
  Thermometer,
  Timer,
  ToggleRight,
  Trash2,
  Trophy,
  Type,
  Wand2,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * Explicit registry for icons that are looked up by name at runtime.
 *
 * Lesson and pathway data store an icon as a string, which previously meant
 * `import * as Icons from 'lucide-react'` and a `(Icons as any)[name]` lookup.
 * A namespace import defeats tree-shaking, so the entire icon set (~570 kB)
 * ended up in the bundle. Listing the 50 names the data actually uses keeps
 * the dynamic lookup working while shipping only those icons.
 *
 * Names are sourced from `icon` fields in constants/lessons.ts.
 */
export const LESSON_ICONS: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  Book,
  Box,
  Calculator,
  Clock,
  Code,
  Cpu,
  Database,
  DatabaseBackup,
  Eye,
  Feather,
  FileText,
  Filter,
  Flame,
  Folder,
  FolderTree,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Infinity,
  Keyboard,
  Layers,
  Layout,
  Link,
  List,
  Lock,
  MoreHorizontal,
  Network,
  Package,
  RefreshCw,
  Repeat,
  Save,
  ScrollText,
  Search,
  Server,
  Settings,
  Shield,
  Terminal,
  TerminalSquare,
  Thermometer,
  Timer,
  ToggleRight,
  Trash2,
  Trophy,
  Type,
  Wand2,
  Zap,
};

/** Resolves a stored icon name, falling back to a neutral glyph. */
export const getLessonIcon = (name: string | undefined): LucideIcon =>
  (name && LESSON_ICONS[name]) || Code;
